### PR TITLE
Add Quote List Page to manage the translation of subtitles

### PR DESCRIPTION
**Pull request by bamboo3250**
1. run `php artisan migrate` 
2. run `gulp`
3. run `php -S localhost:8000` in `\public`
4. go to `http://localhost:8000/data/quotes` to check the UI (the table should be empty for now)
5. put `quotes.json` to `/storage/app/`
6. go to `http://localhost:8000/data/quotes/import` to import the quote into database
7. Now can see the table with some data.
screen shot 2015-11-19 at 8 36 38 am

8. Click on any row to go to the quote list of the corresponding ship.
screen shot 2015-11-19 at 8 36 33 am

### CODE REVIEW

**Comment by dragonjet** [comment]
:+1: good work as usual, we're one step closer to subtitle release
just one thing though, I was able to make it to the big table, just the rows are not clickable to see the #8 interface :laughing:

**Comment by bamboo3250** [comment]
hm probably because the `quotes.js` is not included properly.

screenshot 2015-12-01 04 23 38

Could you check the `/public/js` folder and the `gulpfile.js` file?

**Comment by dragonjet** [comment]
ah sorry i forgot step 2 :laughing: forgot to run `gulp` :v

**Comment by bamboo3250** [comment]
Is there any way to improve the workflow? For the current one, it may not be convenient when a new feature with css and js files is added. Other developers have to do all the steps above to make it work. :sweat_smile: Or is it supposed to be lengthy like that?

**Comment by dragonjet** [comment]
back when we were still using xampp, we didn't need step 3, and probably when I'll also start focusing here, I might re-use xampp to avoid `php artisan serve` (alternative to `php -S localhost:8000`). This is because I'll also need to access mysql thru `localhost/phpmyadmin` which is also build in on xampp

for step 1, i'm alright with it since it's only when there are database changes

for step 2, yes I feel that, needing to `gulp` everytime there's a js/css change is a pain. However, there is `gulp watch` to auto-build as soon as you save it.

**Pull request merged**
